SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


ASTEROID_MIN_RADIUS = 15
ASTEROID_MAX_RADIUS = 50
ASTEROID_SPAWN_RATE = 2  # Čas mezi spawnováním asteroidů (v sekundách)
ASTEROID_KINDS = 3  # Počet různých velikostí asteroidů

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.3

ASTEROID_MIN_RADIUS = 15  # Nejmenší možný asteroid
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2  # Nové asteroidy budou o 20 % rychlejší
ASTEROID_SPLIT_ANGLE_MIN = 20  # Minimální úhel rozdělení
ASTEROID_SPLIT_ANGLE_MAX = 50  # Maximální úhel rozdělení

