SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


ASTEROID_MIN_RADIUS = 15
ASTEROID_MAX_RADIUS = 50
ASTEROID_SPAWN_RATE = 2  # asteroid spawn cooldownd in seconds
ASTEROID_KINDS = 3  # Number of different sizes of asteroids

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.3

ASTEROID_MIN_RADIUS = 15  # The smallest possible asteroid
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2  # New asteroids are 20% faster
ASTEROID_SPLIT_ANGLE_MIN = 20  # Minimal split angle
ASTEROID_SPLIT_ANGLE_MAX = 50  # Maximum split angle

ASTEROID_SCORE_LARGE = 50  # Points for large asteroids
ASTEROID_SCORE_MEDIUM = 75  # Points for medium asteroids
ASTEROID_SCORE_SMALL = 100  # Points for small asteroids
